In [ ]:
n=int(input('TILL how much number you want to febonaci series: '))
x=int(input('Enter the ist value:'))
y=int(input('Enter the 2nd value:'))
while(n<num):
    sum=x+y
    print(sum)
    sum=y
    y=x
    


In [ ]:
print('dhjfgg')

In [ ]:
2020

In [12]:
import bisect
c=[1,2,2,2,3,4,6,7]
bisect.bisect(c,6)

7

In [9]:
c=[1,2,2,2,3,4,6,7]
c[::2]

[1, 2, 3, 6]

In [14]:
a=[9,5,2,1,7,4,5,8,7]
a.sort()
a

[1, 2, 4, 5, 5, 7, 7, 8, 9]

In [23]:
b=['shashi','nishi','papa','mamama']
b.sort(key=len)
b

['papa', 'nishi', 'shashi', 'mamama']

In [44]:
strs=['xc','db','sb','ra','tt']
def myfn(s):
    s[-1]
print(sorted(strs , (key = myfn)) )

SyntaxError: invalid syntax (<ipython-input-44-bad16e625990>, line 4)

In [4]:
import pandas as pd
obj=pd.series(range(4),index=['d','a','b','c'])
obj.sort_index()

AttributeError: module 'pandas' has no attribute 'series'

In [10]:
import pandas as pd
obj=pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [9]:
import pandas as pd
obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
import numpy as np
data=np.random.randn(2,3)
data

array([[-1.2707656 , -1.49012499, -0.94368055],
       [ 1.07584831,  1.81948833, -0.34424754]])

In [17]:
import pandas as pd
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index()
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [20]:
import pandas as pd
obj=pd.Series([7,5,7,4,5,1,2,4,6,5])
obj.rank()

0    9.5
1    6.0
2    9.5
3    3.5
4    6.0
5    1.0
6    2.0
7    3.5
8    8.0
9    6.0
dtype: float64

In [3]:
print('shashi')

shashi


In [20]:
import numpy as np
np.arange(10)
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [44]:
import numpy as np
arr1=np.array([1,2,3])
arr1.astype(np.float32)
arr=np.array([3.7,-10.2,-2.6,12.9,1.1])
arr.astype(np.int32)

array([  3, -10,  -2,  12,   1])

In [45]:
arr1.astype(np.float32)

array([1., 2., 3.], dtype=float32)

In [53]:
numeric_string=np.array(['5','8','8','23','9'])
numeric_string.astype(np.uint16)

array([ 5,  8,  8, 23,  9], dtype=uint16)

In [94]:
s=np.array([1,2,3,4,5,45],dtype=np.int)
p=np.array([9,8,7,6,5])
s+p
s-p
s*5+p
s*2.2*p
1/s
s**32
s>p
p>=s
s[2:8]
p[:4]


NameError: name 'NULL' is not defined

In [76]:
p>s

array([False, False, False, False, False])

In [108]:
l=[1,2,34,5,6]
l_slice=l[2:4]
l_slice[0]=20
l[2]=56
l

[1, 2, 56, 5, 6]

In [106]:
l=[1,2,34,5,6]
l[2]=56
l

[1, 2, 56, 5, 6]

In [152]:
import numpy as np
r=np.array(([[1, 2,3,4,5,9],[1,2,4,5,6,'b'],[1,2,5,8,7,'']])*2)
r.shape
r.dtype
print(r,r[2][1])
r.shape

[['1' '2' '3' '4' '5' '9']
 ['1' '2' '4' '5' '6' 'b']
 ['1' '2' '5' '8' '7' '']
 ['1' '2' '3' '4' '5' '9']
 ['1' '2' '4' '5' '6' 'b']
 ['1' '2' '5' '8' '7' '']] 2


(6, 6)

In [133]:
np.random.rand(2,2)

array([[0.08209928, 0.26778692],
       [0.5759153 , 0.6116973 ]])

In [138]:
r[2][2]

'5'

In [154]:
v=r[1].copy()
r[1]=45
r[1]
r[1]=v
r

array([['1', '2', '3', '4', '5', '9'],
       ['45', '45', '45', '45', '45', '45'],
       ['1', '2', '5', '8', '7', ''],
       ['1', '2', '3', '4', '5', '9'],
       ['1', '2', '4', '5', '6', 'b'],
       ['1', '2', '5', '8', '7', '']], dtype='<U11')

In [157]:
x=np.array([1,2,3,4],dtype=np.float32)
y=np.array([1,2,3,4],dtype=np.int64)
x*y

array([ 1.,  4.,  9., 16.])

In [177]:
array3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array3d
array3d[:2,1:]=0
array3d

array([[[1, 2, 3],
        [0, 0, 0]],

       [[7, 8, 9],
        [0, 0, 0]]])

In [179]:
names=np.array(['Bob','Joe','will','Bob','will','joe','joe'])
data=np.random.randn(7,4)
names
data

array([[-0.26196838,  1.75134495,  0.77868401, -1.06898607],
       [ 0.47614536, -1.62016882, -0.09899059, -0.04177662],
       [ 0.0781773 , -1.2271616 ,  0.44891192, -1.28470654],
       [-1.36544324, -0.35949207, -0.14673965, -1.16599775],
       [-0.04086875,  0.79693901,  0.4178619 , -0.6243846 ],
       [ 0.89195359,  0.24439777,  0.57587564, -0.63654803],
       [-0.20327142,  0.84835091,  1.16912622, -0.4724322 ]])

In [225]:
names == 'Bob'

True

In [182]:
data[names=='Bob']

array([[[-0.26196838,  1.75134495,  0.77868401, -1.06898607],
        [ 0.47614536, -1.62016882, -0.09899059, -0.04177662],
        [ 0.0781773 , -1.2271616 ,  0.44891192, -1.28470654],
        [-1.36544324, -0.35949207, -0.14673965, -1.16599775],
        [-0.04086875,  0.79693901,  0.4178619 , -0.6243846 ],
        [ 0.89195359,  0.24439777,  0.57587564, -0.63654803],
        [-0.20327142,  0.84835091,  1.16912622, -0.4724322 ]]])

In [226]:
data[names=='Bob',:2]

array([[[7., 7., 7., 7.],
        [7., 7., 7., 7.]]])

In [227]:
data[names=='Bob',:3]

array([[[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]])

In [187]:
names !='Bob'

False

In [189]:
data[~(names=='Bob')]

array([ 0.89195359,  0.24439777,  0.57587564, -0.63654803])

In [190]:
coud=names=='Bob'
data[~coud]

array([ 0.89195359,  0.24439777,  0.57587564, -0.63654803])

In [197]:
mask=(names=='Bob')\(names=='will')
mask


SyntaxError: unexpected character after line continuation character (<ipython-input-197-ecfd34765655>, line 1)

In [198]:
data[data<0]=0
data

array([[0.        , 1.75134495, 0.77868401, 0.        ],
       [0.47614536, 0.        , 0.        , 0.        ],
       [0.0781773 , 0.        , 0.44891192, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.79693901, 0.4178619 , 0.        ],
       [0.89195359, 0.24439777, 0.57587564, 0.        ],
       [0.        , 0.84835091, 1.16912622, 0.        ]])

In [199]:
data[names !='joe']=7
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [200]:
print('FANCY INDEXING')

FANCY INDEXING


In [232]:
arr=np.empty((8,4))
for i in range (8):
    arr[i]=i
    
arr[[1,2,4]];arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [234]:

r=np.arange(32).reshape((8,4))
r
arr[[-1,-2,-4]]
                        

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [4., 4., 4., 4.]])

In [248]:
arr[[1,2,3]][:,[1,2,3]]

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [249]:
arr[[1,2,3]][:,[1,2,3]]

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [251]:
E=np.arange(16).reshape((2,2,4))
E

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [253]:
E.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [254]:
E.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [255]:
np.sqrt(E)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [256]:
np.exp(E)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]]])

In [258]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [259]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [261]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [263]:
c=np.random.randn(5)
y=np.random.randn(5)
np.maximum(c,y)

array([ 1.93074841,  0.45569026,  1.11685672,  0.25510458, -0.11775268])

In [268]:
arr=np.random.randn(5)*5
arr
reminder,whole_part=np.modf(arr)
whole_part
reminder

array([ 0.32929372, -0.63179937, -0.29028221,  0.07778306, -0.97146639])

In [277]:
arr=np.array([[1,2,3,4],[1,2,3,4]])
arr
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [278]:
np.dot(arr.T,arr)

array([[ 2,  4,  6,  8],
       [ 4,  8, 12, 16],
       [ 6, 12, 18, 24],
       [ 8, 16, 24, 32]])

In [282]:
import matplotlib.pyplot as plt
from datetime import datetime
fig = plt.figure()
ax=fig.add_subplot(1,1,1)
data=pd.read_csv('examples/spx.csv',index_col=0,parse_dates=True)
spx=data['spx']
spx.plot(ax=ax,style='k-')
crisis_data=[
    (datetime(2007,10,11),'peak of bull market'),
    (datetime(2008,3,12),'Bear stearms Fails'),
    (datetime(2008,9,15),'Lehman Bankruptcy')
]
for date, label in crisis_data:
    ax.annotate(lebel,xy=(date,spx.asof(date)+75),xytext=(date,spx.asof(data)+225),arrowprops=dict(facecolor='blank',headwidth=4,width=2,headlength=4),horizontalignment='left',verticalalignment='top')
    ax.set_xlim(['1/1/2007','1/1/2011'])
    ax.set_ylim([600,1800])
    ax.set_title('important dates in 2007-2009 financial crisis')

NameError: name 'pd' is not defined

In [285]:
points=np.arange(-5,5,0.01)
type(points)
xs,ys=np.meshgrid(points,points)
xs
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [289]:
arr=np.random.rand(4)
arr
arr.sort()
arr

array([0.38287326, 0.71324141, 0.76764362, 0.99431138])

In [301]:
X=np.array([[1,2,3,4,2],[9,8,76,5,6],[12,52,47,85,12],[1,2,7,5,3]])

X

array([[ 1,  2,  3,  4,  2],
       [ 9,  8, 76,  5,  6],
       [12, 52, 47, 85, 12],
       [ 1,  2,  7,  5,  3]])

In [309]:
X.sort(0)
X

array([[ 1,  2,  2,  3,  4],
       [ 1,  2,  3,  5,  7],
       [ 5,  6,  8,  9, 76],
       [12, 12, 47, 52, 85]])

In [310]:
names=np.array(['Bob','Joe','will','Bob','will','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will', 'will'], dtype='<U4')

In [312]:
T=np.array([3,3,3,2,2,2,5,8,7,5,8,7,5,8,7,7,8,4,5,4,8,4,65,4,4,5,4,5,4,5,4,5,])
np.unique(T)

array([ 2,  3,  4,  5,  7,  8, 65])